name: Pack source code & Create CI/CD Release

on:
  # 任意分支每次 push 都触发一次自动构建
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  pack:
    name: Pack

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
        with:
          path: "./HugoAura-Code"

      - name: Create aura.zip
        run: |
          echo "[DEBUG] Creating artifacts directory"
          mkdir -p Artifacts
          cd ./HugoAura-Code/src/aura
          zip -r ../../../Artifacts/aura.zip .
          cd ../core
          zip -r ../../../Artifacts/core.zip .
          cd ../../..

          echo "[DEBUG] Files in <Working DIR>/Artifacts directory:"
          ls -la Artifacts/

      - name: Get commit hash & build time
        run: |
          cd ./HugoAura-Code
          SHORT_HASH=$(git rev-parse --short=7 HEAD)
          FULL_HASH=$(git rev-parse HEAD)
          echo "SHORT_HASH=$SHORT_HASH" >> $GITHUB_ENV
          echo "FULL_HASH=$FULL_HASH" >> $GITHUB_ENV
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV

      - name: Create release content
        run: |
          cat > rel_msg.txt << 'EOF'
          ## 这是 HugoAura 的 CI 自动构建版本

          ### 版本类型: 🔁 自动构建版

          ### 版本号: `vAutoBuild-${{ env.SHORT_HASH }}`

          ### 对应 Commit: [`${{ env.SHORT_HASH }}`](https://github.com/${{ github.repository }}/commit/${{ env.FULL_HASH }})

          ---

          ### ⚠ 注意: CI 自动构建版本可能不稳定 / 存在较多 Bug, 更新时请留意

          #### 🕘 构建时间: ${{ env.BUILDTIME }}
          EOF

      - name: Upload aura.zip
        uses: actions/upload-artifact@v7
        with:
          name: aura-code
          path: Artifacts/aura.zip

      - name: Upload core.zip
        uses: actions/upload-artifact@v7
        with:
          name: aura-core
          path: Artifacts/core.zip

      - name: Upload release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create vAutoBuild-${{ env.SHORT_HASH }} Artifacts/aura.zip Artifacts/core.zip --title "[CI] HugoAura Auto Build Release (${{ env.SHORT_HASH }})" --notes-file rel_msg.txt --prerelease
